### ISSUE TITLE
`recommended` config should configure plugin

### ISSUE THREAD

**Issue by SchroederSteffen** [maks-rafalko/eslint-plugin-proper-tests#7]
Hi,

Some very nice rules! I'm hoping to introduce this plugin in our corporate projects soon.

One suggestion though:
Currently, we have to configure `"plugins": ["proper-tests"]` manually in order to use the recommended config as `"extends": ["plugin:proper-tests/recommended"]` (as documented in the README) .
However, if the config would include that line itself, this wouldn't be necessary making the consumption easier.

Including it seems to be common practice and is done by most other plugins we use.

Examples:
- https://github.com/jest-community/eslint-plugin-jest/blob/3888beea7b0db48e017d3e696fca8b8aef988dea/src/index.ts#L90
- https://github.com/typescript-eslint/typescript-eslint/blob/3f02687d964c1e7888e5db62256d56cd72c4f281/packages/eslint-plugin/src/configs/base.ts#L6

Cheers,
Steffen

**Comment by maks-rafalko** [comment]
Thank you for your interest and kind words! 

Looking forward to see how it works for your projects. If you have other ideas, feel free to file an issue with suggestions or even make a PR.

Regarding this recommendation - cool, implemented. I will create a new release soon.

**Comment by maks-rafalko** [comment]
Released as [1.0.10](https://www.npmjs.com/package/eslint-plugin-proper-tests/v/1.0.10)
